THIRD_PARTY_LICENSES.txt
verrazzano/keycloak pull request #11
Opened 2021-11-09 19:27 UTC by shihchang

update THIRD_PARTY_LICENSES.txt

2021-11-09 20:56 UTC, markxnelson requested changes

2021-11-09 20:56 UTC, markxnelson commented on THIRD_PARTY_LICENSES.txt
> +If distribution of executable or object code is made
this should not be here

2021-11-09 23:16 UTC, shihchang commented on THIRD_PARTY_LICENSES.txt
> +If distribution of executable or object code is made
removed the chunk of code at the bottom. replaced it to the content of that licenseText.

2021-11-12 18:00 UTC, markxnelson requested changes

2021-11-12 18:00 UTC, markxnelson commented on known_licenses.txt
> +babel-plugin-syntax-class-properties@6.13.0 MIT
this file cannot be checked int

2021-11-15 13:47 UTC, shihchang commented on known_licenses.txt
> +babel-plugin-syntax-class-properties@6.13.0 MIT
removed

2021-11-15 13:51 UTC, markxnelson approved these changes

2021-11-15 15:30 UTC, merged